export const ENTITY = {
  CLIENT: 'CLIENT',
  EMPLOYEE: 'EMPLOYEE',
  SITE: 'SITE',
  GATE: 'GATE',
  SHIFT: 'SHIFT',
  PATROL: 'PATROL',
  INCIDENT: 'INCIDENT',
  ASSIGNMENT: 'ASN',
  PATROL_SESSION: 'PATROL_SESSION',
} as const;
