export const PREFIX = {
  CLIENT: 'CLIENT',
  EMPLOYEE: 'EMP',
  SITE: 'SITE',
  GATE: 'GATE',
  SHIFT: 'SHIFT',
  PATROL: 'PATROL',
  INCIDENT: 'INC',
  ASSIGNMENT: 'ASN',
  PATROL_SESSION: 'PATROL-SESSION',
} as const;
