export const ErrorCodes = {
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',

  VALIDATION_ERROR: 'VALIDATION_ERROR',

  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',

  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  CLIENT_INACTIVE: 'CLIENT_INACTIVE',
  USER_ALREADY_LOGGED_IN: 'USER_ALREADY_LOGGED_IN',

  SITE_NOT_FOUND: 'SITE_NOT_FOUND',
  GUARD_NOT_FOUND: 'GUARD_NOT_FOUND',
  SHIFT_ALREADY_STARTED: 'SHIFT_ALREADY_STARTED',
  INVALID_QR_CODE: 'INVALID_QR_CODE',
} as const;
