packages:
  - 'apps/*'
  - 'libs/*'
  - 'api'
  - 'api-e2e'
  - 'web'
allowBuilds:
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  '@swc/core': true
  bcrypt: true
  esbuild: true
  less: true
  nx: true
  prisma: true
  sharp: true
  unrs-resolver: true
